# Generated by Django 6.1 on 2026-09-18 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_application_cover_letter_and_more'),
        ('vacancies', '0002_alter_vacancy_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='vacancies.vacancy'),
        ),
    ]
